-- Auralis Frost Colorblind community fixture — generated from Auralis roles.
vim.cmd('highlight clear')
vim.o.background = "dark"
vim.g.colors_name = "auralis-frost-colorblind"

vim.api.nvim_set_hl(0, "Normal", { fg = "#ddeff5", bg = "#060e14" })
vim.api.nvim_set_hl(0, "NormalFloat", { fg = "#ddeff5", bg = "#040a10" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#0d171f" })
vim.api.nvim_set_hl(0, "Visual", { bg = "#00758c" })
vim.api.nvim_set_hl(0, "Comment", { fg = "#6b7d8b", italic = true })
vim.api.nvim_set_hl(0, "String", { fg = "#f3ae58" })
vim.api.nvim_set_hl(0, "Number", { fg = "#ff9173" })
vim.api.nvim_set_hl(0, "Keyword", { fg = "#a8a2ff" })
vim.api.nvim_set_hl(0, "Function", { fg = "#00e2ff" })
vim.api.nvim_set_hl(0, "Type", { fg = "#60e7d8" })
vim.api.nvim_set_hl(0, "Identifier", { fg = "#7adaf8" })
vim.api.nvim_set_hl(0, "Operator", { fg = "#b2adff" })
vim.api.nvim_set_hl(0, "Delimiter", { fg = "#88949d" })
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#fc984c" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = "#e6b816" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = "#60e7d8" })
vim.api.nvim_set_hl(0, "DiffAdd", { fg = "#00cef3" })
vim.api.nvim_set_hl(0, "DiffDelete", { fg = "#fc984c" })
vim.api.nvim_set_hl(0, "DiffChange", { fg = "#e6b816" })

vim.api.nvim_set_hl(0, "@comment", { link = "Comment" })
vim.api.nvim_set_hl(0, "@string", { link = "String" })
vim.api.nvim_set_hl(0, "@number", { link = "Number" })
vim.api.nvim_set_hl(0, "@keyword", { link = "Keyword" })
vim.api.nvim_set_hl(0, "@function", { link = "Function" })
vim.api.nvim_set_hl(0, "@type", { link = "Type" })
vim.api.nvim_set_hl(0, "@property", { link = "Identifier" })
vim.api.nvim_set_hl(0, "@operator", { link = "Operator" })
vim.api.nvim_set_hl(0, "@punctuation", { link = "Delimiter" })
