-- Auralis Noir community fixture — generated from Auralis roles.
vim.cmd('highlight clear')
vim.o.background = "dark"
vim.g.colors_name = "auralis-noir"

vim.api.nvim_set_hl(0, "Normal", { fg = "#e9e4dc", bg = "#0f1117" })
vim.api.nvim_set_hl(0, "NormalFloat", { fg = "#e9e4dc", bg = "#0c0e14" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#181a21" })
vim.api.nvim_set_hl(0, "Visual", { bg = "#194f81" })
vim.api.nvim_set_hl(0, "Comment", { fg = "#747d96", italic = true })
vim.api.nvim_set_hl(0, "String", { fg = "#e1c34b" })
vim.api.nvim_set_hl(0, "Number", { fg = "#ff9381" })
vim.api.nvim_set_hl(0, "Keyword", { fg = "#f47db9" })
vim.api.nvim_set_hl(0, "Function", { fg = "#25d2fc" })
vim.api.nvim_set_hl(0, "Type", { fg = "#52dfbf" })
vim.api.nvim_set_hl(0, "Identifier", { fg = "#e6bd77" })
vim.api.nvim_set_hl(0, "Operator", { fg = "#ce84a7" })
vim.api.nvim_set_hl(0, "Delimiter", { fg = "#8a8f9c" })
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#fc5855" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = "#e9ab2b" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = "#52dfbf" })
vim.api.nvim_set_hl(0, "DiffAdd", { fg = "#6ec272" })
vim.api.nvim_set_hl(0, "DiffDelete", { fg = "#fc5855" })
vim.api.nvim_set_hl(0, "DiffChange", { fg = "#e9ab2b" })

vim.api.nvim_set_hl(0, "@comment", { link = "Comment" })
vim.api.nvim_set_hl(0, "@string", { link = "String" })
vim.api.nvim_set_hl(0, "@number", { link = "Number" })
vim.api.nvim_set_hl(0, "@keyword", { link = "Keyword" })
vim.api.nvim_set_hl(0, "@function", { link = "Function" })
vim.api.nvim_set_hl(0, "@type", { link = "Type" })
vim.api.nvim_set_hl(0, "@property", { link = "Identifier" })
vim.api.nvim_set_hl(0, "@operator", { link = "Operator" })
vim.api.nvim_set_hl(0, "@punctuation", { link = "Delimiter" })
