-- Auralis Dimmed community fixture — generated from Auralis roles.
vim.cmd('highlight clear')
vim.o.background = "dark"
vim.g.colors_name = "auralis-dimmed"

vim.api.nvim_set_hl(0, "Normal", { fg = "#d4d0ca", bg = "#080a0d" })
vim.api.nvim_set_hl(0, "NormalFloat", { fg = "#d4d0ca", bg = "#05080a" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#0e1215" })
vim.api.nvim_set_hl(0, "Visual", { bg = "#004859" })
vim.api.nvim_set_hl(0, "Comment", { fg = "#6f7e8d", italic = true })
vim.api.nvim_set_hl(0, "String", { fg = "#beaa5e" })
vim.api.nvim_set_hl(0, "Number", { fg = "#ff9381" })
vim.api.nvim_set_hl(0, "Keyword", { fg = "#c57fbf" })
vim.api.nvim_set_hl(0, "Function", { fg = "#41bdd1" })
vim.api.nvim_set_hl(0, "Type", { fg = "#6fc4ae" })
vim.api.nvim_set_hl(0, "Identifier", { fg = "#e6bd77" })
vim.api.nvim_set_hl(0, "Operator", { fg = "#ce84a7" })
vim.api.nvim_set_hl(0, "Delimiter", { fg = "#8a8f9c" })
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#fc5855" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = "#e9ab2b" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = "#6fc4ae" })
vim.api.nvim_set_hl(0, "DiffAdd", { fg = "#6ec272" })
vim.api.nvim_set_hl(0, "DiffDelete", { fg = "#fc5855" })
vim.api.nvim_set_hl(0, "DiffChange", { fg = "#e9ab2b" })

vim.api.nvim_set_hl(0, "@comment", { link = "Comment" })
vim.api.nvim_set_hl(0, "@string", { link = "String" })
vim.api.nvim_set_hl(0, "@number", { link = "Number" })
vim.api.nvim_set_hl(0, "@keyword", { link = "Keyword" })
vim.api.nvim_set_hl(0, "@function", { link = "Function" })
vim.api.nvim_set_hl(0, "@type", { link = "Type" })
vim.api.nvim_set_hl(0, "@property", { link = "Identifier" })
vim.api.nvim_set_hl(0, "@operator", { link = "Operator" })
vim.api.nvim_set_hl(0, "@punctuation", { link = "Delimiter" })
