-- Syntalume Botanica community fixture — generated from Syntalume roles.
vim.cmd('highlight clear')
vim.o.background = "dark"
vim.g.colors_name = "syntalume-botanica"

vim.api.nvim_set_hl(0, "Normal", { fg = "#e5e6d7", bg = "#0e1913" })
vim.api.nvim_set_hl(0, "NormalFloat", { fg = "#e5e6d7", bg = "#0b1510" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#15211a" })
vim.api.nvim_set_hl(0, "Visual", { bg = "#2c6330" })
vim.api.nvim_set_hl(0, "Comment", { fg = "#768776", italic = true })
vim.api.nvim_set_hl(0, "String", { fg = "#e1c34b" })
vim.api.nvim_set_hl(0, "Number", { fg = "#f8a052" })
vim.api.nvim_set_hl(0, "Keyword", { fg = "#f97770" })
vim.api.nvim_set_hl(0, "Function", { fg = "#a1d862" })
vim.api.nvim_set_hl(0, "Type", { fg = "#68e4c6" })
vim.api.nvim_set_hl(0, "Identifier", { fg = "#95cf96" })
vim.api.nvim_set_hl(0, "Operator", { fg = "#e3928b" })
vim.api.nvim_set_hl(0, "Delimiter", { fg = "#899287" })
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#fc5855" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = "#e6ac3d" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = "#68e4c6" })
vim.api.nvim_set_hl(0, "DiffAdd", { fg = "#68cb6e" })
vim.api.nvim_set_hl(0, "DiffDelete", { fg = "#fc5855" })
vim.api.nvim_set_hl(0, "DiffChange", { fg = "#e6ac3d" })

vim.api.nvim_set_hl(0, "@comment", { link = "Comment" })
vim.api.nvim_set_hl(0, "@string", { link = "String" })
vim.api.nvim_set_hl(0, "@number", { link = "Number" })
vim.api.nvim_set_hl(0, "@keyword", { link = "Keyword" })
vim.api.nvim_set_hl(0, "@function", { link = "Function" })
vim.api.nvim_set_hl(0, "@type", { link = "Type" })
vim.api.nvim_set_hl(0, "@property", { link = "Identifier" })
vim.api.nvim_set_hl(0, "@operator", { link = "Operator" })
vim.api.nvim_set_hl(0, "@punctuation", { link = "Delimiter" })
