-- Syntalume Paper community fixture — generated from Syntalume roles.
vim.cmd('highlight clear')
vim.o.background = "light"
vim.g.colors_name = "syntalume-paper"

vim.api.nvim_set_hl(0, "Normal", { fg = "#352c25", bg = "#faf4ec" })
vim.api.nvim_set_hl(0, "NormalFloat", { fg = "#352c25", bg = "#f3ede6" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#f2eae0" })
vim.api.nvim_set_hl(0, "Visual", { bg = "#f0a08c" })
vim.api.nvim_set_hl(0, "Comment", { fg = "#7e6d56", italic = true })
vim.api.nvim_set_hl(0, "String", { fg = "#1e7729" })
vim.api.nvim_set_hl(0, "Number", { fg = "#b25400" })
vim.api.nvim_set_hl(0, "Keyword", { fg = "#ad215f" })
vim.api.nvim_set_hl(0, "Function", { fg = "#044cb6" })
vim.api.nvim_set_hl(0, "Type", { fg = "#007982" })
vim.api.nvim_set_hl(0, "Identifier", { fg = "#6d3800" })
vim.api.nvim_set_hl(0, "Operator", { fg = "#a43c2f" })
vim.api.nvim_set_hl(0, "Delimiter", { fg = "#756b63" })
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#cc272e" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = "#bb6a00" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = "#007982" })
vim.api.nvim_set_hl(0, "DiffAdd", { fg = "#308639" })
vim.api.nvim_set_hl(0, "DiffDelete", { fg = "#cc272e" })
vim.api.nvim_set_hl(0, "DiffChange", { fg = "#bb6a00" })

vim.api.nvim_set_hl(0, "@comment", { link = "Comment" })
vim.api.nvim_set_hl(0, "@string", { link = "String" })
vim.api.nvim_set_hl(0, "@number", { link = "Number" })
vim.api.nvim_set_hl(0, "@keyword", { link = "Keyword" })
vim.api.nvim_set_hl(0, "@function", { link = "Function" })
vim.api.nvim_set_hl(0, "@type", { link = "Type" })
vim.api.nvim_set_hl(0, "@property", { link = "Identifier" })
vim.api.nvim_set_hl(0, "@operator", { link = "Operator" })
vim.api.nvim_set_hl(0, "@punctuation", { link = "Delimiter" })
