-- Syntalume Void community fixture — generated from Syntalume roles.
vim.cmd('highlight clear')
vim.o.background = "dark"
vim.g.colors_name = "syntalume-void"

vim.api.nvim_set_hl(0, "Normal", { fg = "#e1ded5", bg = "#000000" })
vim.api.nvim_set_hl(0, "NormalFloat", { fg = "#e1ded5", bg = "#000000" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#060509" })
vim.api.nvim_set_hl(0, "Visual", { bg = "#004985" })
vim.api.nvim_set_hl(0, "Comment", { fg = "#757387", italic = true })
vim.api.nvim_set_hl(0, "String", { fg = "#96d987" })
vim.api.nvim_set_hl(0, "Number", { fg = "#ffa746" })
vim.api.nvim_set_hl(0, "Keyword", { fg = "#c787ff" })
vim.api.nvim_set_hl(0, "Function", { fg = "#00dffd" })
vim.api.nvim_set_hl(0, "Type", { fg = "#5ae6c6" })
vim.api.nvim_set_hl(0, "Identifier", { fg = "#85cff3" })
vim.api.nvim_set_hl(0, "Operator", { fg = "#c49bf3" })
vim.api.nvim_set_hl(0, "Delimiter", { fg = "#868492" })
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#fc5855" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = "#e6b22d" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = "#5ae6c6" })
vim.api.nvim_set_hl(0, "DiffAdd", { fg = "#61cb7c" })
vim.api.nvim_set_hl(0, "DiffDelete", { fg = "#fc5855" })
vim.api.nvim_set_hl(0, "DiffChange", { fg = "#e6b22d" })

vim.api.nvim_set_hl(0, "@comment", { link = "Comment" })
vim.api.nvim_set_hl(0, "@string", { link = "String" })
vim.api.nvim_set_hl(0, "@number", { link = "Number" })
vim.api.nvim_set_hl(0, "@keyword", { link = "Keyword" })
vim.api.nvim_set_hl(0, "@function", { link = "Function" })
vim.api.nvim_set_hl(0, "@type", { link = "Type" })
vim.api.nvim_set_hl(0, "@property", { link = "Identifier" })
vim.api.nvim_set_hl(0, "@operator", { link = "Operator" })
vim.api.nvim_set_hl(0, "@punctuation", { link = "Delimiter" })
