-- Syntalume Noir High Contrast community fixture — generated from Syntalume roles.
vim.cmd('highlight clear')
vim.o.background = "dark"
vim.g.colors_name = "syntalume-noir-high-contrast"

vim.api.nvim_set_hl(0, "Normal", { fg = "#faf6ef", bg = "#040508" })
vim.api.nvim_set_hl(0, "NormalFloat", { fg = "#faf6ef", bg = "#030306" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#101219" })
vim.api.nvim_set_hl(0, "Visual", { bg = "#286cab" })
vim.api.nvim_set_hl(0, "Comment", { fg = "#8791af", italic = true })
vim.api.nvim_set_hl(0, "String", { fg = "#e1c34b" })
vim.api.nvim_set_hl(0, "Number", { fg = "#ff9381" })
vim.api.nvim_set_hl(0, "Keyword", { fg = "#f47db9" })
vim.api.nvim_set_hl(0, "Function", { fg = "#25d2fc" })
vim.api.nvim_set_hl(0, "Type", { fg = "#52dfbf" })
vim.api.nvim_set_hl(0, "Identifier", { fg = "#e6bd77" })
vim.api.nvim_set_hl(0, "Operator", { fg = "#ce84a7" })
vim.api.nvim_set_hl(0, "Delimiter", { fg = "#b7bdce" })
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#fc5855" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = "#e9ab2b" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = "#52dfbf" })
vim.api.nvim_set_hl(0, "DiffAdd", { fg = "#6ec272" })
vim.api.nvim_set_hl(0, "DiffDelete", { fg = "#fc5855" })
vim.api.nvim_set_hl(0, "DiffChange", { fg = "#e9ab2b" })

vim.api.nvim_set_hl(0, "@comment", { link = "Comment" })
vim.api.nvim_set_hl(0, "@string", { link = "String" })
vim.api.nvim_set_hl(0, "@number", { link = "Number" })
vim.api.nvim_set_hl(0, "@keyword", { link = "Keyword" })
vim.api.nvim_set_hl(0, "@function", { link = "Function" })
vim.api.nvim_set_hl(0, "@type", { link = "Type" })
vim.api.nvim_set_hl(0, "@property", { link = "Identifier" })
vim.api.nvim_set_hl(0, "@operator", { link = "Operator" })
vim.api.nvim_set_hl(0, "@punctuation", { link = "Delimiter" })
