# Auralis Void for kitty — generated community fixture.
foreground #e1ded5
background #000000
cursor #00efff
selection_background #004985
color0 #000000
color1 #fc5855
color2 #61cb7c
color3 #e6b22d
color4 #00dffd
color5 #c787ff
color6 #5ae6c6
color7 #e1ded5
color8 #696870
color9 #ff625f
color10 #65e287
color11 #ffc31a
color12 #00f6ff
color13 #de95ff
color14 #50fed8
color15 #eeebe2
