# Syntalume Frost for kitty — generated community fixture.
foreground #ddeff5
background #02080e
cursor #00f2ff
selection_background #007b87
color0 #060e14
color1 #ff5169
color2 #00d097
color3 #e6b816
color4 #00e5f2
color5 #a688ff
color6 #48e8c5
color7 #ddeff5
color8 #5b6c74
color9 #ff5b75
color10 #00e7a7
color11 #ffca00
color12 #00fcff
color13 #b997ff
color14 #38ffd8
color15 #ebfcff
