# Syntalume Botanica for kitty — generated community fixture.
foreground #e5e6d7
background #08130d
cursor #a6e45a
selection_background #2c6330
color0 #0e1913
color1 #fc5855
color2 #68cb6e
color3 #e6ac3d
color4 #a1d862
color5 #e29936
color6 #68e4c6
color7 #e5e6d7
color8 #616c63
color9 #ff625f
color10 #6fe276
color11 #ffbd34
color12 #b0ee65
color13 #fea92f
color14 #62fcd9
color15 #f2f3e4
