# Syntalume Noir High Contrast for kitty — generated community fixture.
foreground #faf6ef
background #020305
cursor #ffac67
selection_background #286cab
color0 #040508
color1 #fc5855
color2 #6ec272
color3 #e9ab2b
color4 #25d2fc
color5 #e175d9
color6 #52dfbf
color7 #faf6ef
color8 #8e929e
color9 #ff625f
color10 #75d87a
color11 #ffbc19
color12 #00e8ff
color13 #fc82f3
color14 #47f7d2
color15 #fcf8f1
